services:
  - type: web
    name: libretranslate
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: LT_HOST
        value: "0.0.0.0"
      - key: LT_PORT
        value: "5000"